language: java
jdk:
- oraclejdk8
os:
- linux
sudo: required
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install:
- echo "utils_dev";
- echo "Test";
jobs:
  include: 
  - stage: Main Build Test
    before_script: cd utils_dev
    - script: ant build
    - script: cd adempiere/Adempiere
    - script: ./RUN_silentsetup.sh
  - stage: Run Silest Setup
notifications:
  email:
    recipients:
    - ysenih@erpya.com
    on_failure: always
