language: java
jdk:
- oraclejdk8
os:
- linux
sudo: required
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install:
- echo "utils_dev";
before_script: cd utils_dev
script: ant build
before_script: cd adempiere/Adempiere
script: ./RUN_silentsetup.sh
notifications:
  email:
    recipients:
    - ysenih@erpya.com
    on_failure: always
