language: java
jdk:
- oraclejdk8
os:
- linux
sudo: required
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install:
- echo "utils_dev";
- echo "Test";
jobs:
  include:
  - stage: Main Build Test
    script: ant build
notifications:
  email:
    recipients:
    - ysenih@erpya.com
    on_failure: always
