language: java
jdk:
- oraclejdk8
os:
- linux
sudo: required
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install:
- echo "utils_dev";
jobs:
  include:
  - stage: Main Build Test
    script: ant utils_dev/build
  - stage: Run Silest Setup
    script: bash adempiere/Adempiere/RUN_silentsetup.sh
notifications:
  email:
    recipients:
    - ysenih@erpya.com
    on_failure: always
